# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-f9107631-e0e3-4ff8-8e63-fec31633a1d5";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-f9107631-e0e3-4ff8-8e63-fec31633a1d5".device = "/dev/disk/by-uuid/f9107631-e0e3-4ff8-8e63-fec31633a1d5";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-f9107631-e0e3-4ff8-8e63-fec31633a1d5";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-f9107631-e0e3-4ff8-8e63-fec31633a1d5";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8CC1-1086";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-81d4d08c-ebe4-4b8a-bd88-c8f664e37a4d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
