{ config, lib, pkgs, ... }:

let
  cfg = config.features.work-vpn;
  has = config.host.has;

  # strongswan 6 dropped the ikev1 implementation entirely, and l2tp/ipsec with
  # a pre-shared key is ikev1 -- charon starts fine and then answers the
  # initiate with "IKE version 1 not supported". libreswan still implements it.
  #
  # the plugin picks its daemon at runtime by running the ipsec binary nixpkgs
  # patches into it and matching the vendor string in --version, so swapping
  # the input over is enough to move it onto libreswan wholesale.
  plugin = pkgs.networkmanager-l2tp.override { strongswan = pkgs.libreswan; };
in
{
  options.features.work-vpn = {
    enable = lib.mkEnableOption "work l2tp/ipsec vpn" // {
      default = has "work" && config.features.networkmanager.enable;
    };

    profile = lib.mkEnableOption "a declarative connection profile built from secretsFile";

    secretsFile = lib.mkOption {
      type = lib.types.path;
      default = "/etc/secrets/work-vpn.env";
      description = ''
        Environment file, deliberately outside this repo, holding every value
        the connection needs:

        ```
        WORK_VPN_GATEWAY=
        WORK_VPN_DOMAIN=
        WORK_VPN_USER=
        WORK_VPN_PASSWORD=
        WORK_VPN_PSK=
        ```

        Nothing here is a secret in the credential sense alone, but a nix file
        ends up world-readable in the store and this repo is public, so the
        server, the account and the domain stay out of it too. envsubst pulls
        them in at activation time.
      '';
    };
  };

  config = lib.mkIf cfg.enable (lib.mkMerge [
    {
      networking.networkmanager.plugins = [ plugin ];

      systemd.tmpfiles.rules = [
        # the plugin writes the psk to /etc/ipsec.d/ipsec.nm-l2tp.secrets, which
        # the /etc/ipsec.secrets generated by the networkmanager module includes,
        # but it never creates the directory itself and just fails the connection
        # instead.
        "d /etc/ipsec.d 0700 root root -"

        # deliberately not gated on profile below: the secrets file has to be in
        # place before the profile exists, or activation trips over the missing
        # EnvironmentFile. so hand out the directory as soon as the feature is on.
        "d ${dirOf cfg.secretsFile} 0700 root root -"
      ];

      # /run/pluto and the /var/lib/ipsec/nss the database lives in
      systemd.tmpfiles.packages = [ pkgs.libreswan ];

      # pluto is started by the package unit against this file, and the per
      # connection config the plugin hands to `ipsec add` cannot override a
      # global. libreswan 5 defaults to ikev1-policy=drop, which refuses the
      # connection at load time: "global ikev1-policy=drop does not allow IKEv1
      # connections". l2tp/ipsec with a pre-shared key is ikev1, so it has to be
      # accepted here. otherwise this matches the file the package ships.
      environment.etc."ipsec.conf".text = lib.mkDefault ''
        config setup
          ikev1-policy=accept

        include /etc/ipsec.d/*.conf
      '';

      # libreswan's `ipsec start` is a wrapper that defers to `systemctl start
      # ipsec.service`, so the unit the package ships has to be installed or the
      # plugin dies on "Unit ipsec.service not found". no wantedBy: pluto only
      # needs to run while the vpn is up, and the plugin starts it on demand.
      systemd.packages = [ pkgs.libreswan ];

      # the unit's ExecStartPre (checknss, checknflog) and pluto itself shell out
      # to these; the package unit carries no path of its own.
      systemd.services.ipsec.path = with pkgs; [
        libreswan
        iproute2
        procps
        nssTools
        iptables
        nettools
      ];

      # `ipsec` is a shell script that shells out to the same set, and it is
      # networkmanager that spawns it, so they have to be on *its* path too.
      systemd.services.NetworkManager.path = with pkgs; [
        libreswan
        iproute2
        procps
        nssTools
        iptables
        nettools
      ];

      # xl2tpd's kernel-mode pppol2tp tunnel, plus mppe for servers that negotiate
      # it on top of the ipsec transport.
      boot.kernelModules = [ "l2tp_ppp" "ppp_mppe" ];

      # nm-connection-editor: noctalia's network panel only does wifi, and the
      # l2tp plugin ships its vpn dialog as a gtk editor this picks up.
      environment.systemPackages = lib.optional (has "ui") pkgs.networkmanagerapplet;
    }

    (lib.mkIf cfg.profile {
      networking.networkmanager.ensureProfiles = {
        environmentFiles = [ cfg.secretsFile ];

        # envsubst runs over this on activation, so the $-variables are the only
        # things that never touch the store. The profile lands in
        # /run/NetworkManager/system-connections and is read-only to the gui;
        # editing it there makes networkmanager fork a second, persistent copy.
        profiles.work-vpn = {
          connection = {
            id = "work";
            uuid = "748968cb-7e45-4072-bc4c-1417279bd2b3";
            type = "vpn";
            autoconnect = false;
          };

          vpn = {
            service-type = "org.freedesktop.NetworkManager.l2tp";
            gateway = "$WORK_VPN_GATEWAY";
            user = "$WORK_VPN_USER";
            domain = "$WORK_VPN_DOMAIN";
            user-auth-type = "password";
            password-flags = 0;
            ipsec-enabled = "yes";
            machine-auth-type = "psk";
            ipsec-psk-flags = 0;
          };

          vpn-secrets = {
            password = "$WORK_VPN_PASSWORD";
            ipsec-psk = "$WORK_VPN_PSK";
          };

          ipv4.method = "auto";
          ipv6 = {
            method = "auto";
            addr-gen-mode = "stable-privacy";
          };
        };
      };
    })
  ]);
}
