{ config, lib, pkgs, ... }:

let
  cfg = config.features.work-vpn;
  has = config.host.has;
in
{
  options.features.work-vpn = {
    enable = lib.mkEnableOption "work l2tp/ipsec vpn" // {
      default = has "work" && config.features.networkmanager.enable;
    };

    profile = lib.mkEnableOption "a declarative connection profile built from secretsFile";

    secretsFile = lib.mkOption {
      type = lib.types.path;
      default = "/etc/secrets/work-vpn.env";
      description = ''
        Environment file, deliberately outside this repo, holding every value
        the connection needs:

        ```
        WORK_VPN_GATEWAY=
        WORK_VPN_DOMAIN=
        WORK_VPN_USER=
        WORK_VPN_PASSWORD=
        WORK_VPN_PSK=
        ```

        Nothing here is a secret in the credential sense alone, but a nix file
        ends up world-readable in the store and this repo is public, so the
        server, the account and the domain stay out of it too. envsubst pulls
        them in at activation time.
      '';
    };
  };

  config = lib.mkIf cfg.enable (lib.mkMerge [
    {
      networking.networkmanager.plugins = [ pkgs.networkmanager-l2tp ];

      systemd.tmpfiles.rules = [
        # the plugin writes the psk to /etc/ipsec.d/ipsec.nm-l2tp.secrets, which
        # the /etc/ipsec.secrets generated by the networkmanager module includes,
        # but it never creates the directory itself and just fails the connection
        # instead.
        "d /etc/ipsec.d 0700 root root -"

        # deliberately not gated on profile below: the secrets file has to be in
        # place before the profile exists, or activation trips over the missing
        # EnvironmentFile. so hand out the directory as soon as the feature is on.
        "d ${dirOf cfg.secretsFile} 0700 root root -"
      ];

      # strongswan aborts library_init outright when /etc/strongswan.conf is
      # missing ("no files found matching" -> "abort initialization due to
      # invalid configuration"), and nixpkgs ships its config only as templates
      # under share/strongswan. the starter reports that as exit code 64, which
      # it prints as "integrity test of libstrongswan failed" -- nothing to do
      # with integrity.
      #
      # the upstream template can't be used verbatim either: it sets
      # load_modular = yes, and every plugin snippet nixpkgs installs under
      # strongswan.d is zero-length, so charon resolves no crypto at all and
      # dies on "unmet dependency: NONCE_GEN". an empty charon block skips
      # modular loading and keeps the compiled-in plugin list.
      environment.etc."strongswan.conf".text = lib.mkDefault ''
        charon {
        }
      '';

      # xl2tpd's kernel-mode pppol2tp tunnel, plus mppe for servers that negotiate
      # it on top of the ipsec transport.
      boot.kernelModules = [ "l2tp_ppp" "ppp_mppe" ];

      # nm-connection-editor: noctalia's network panel only does wifi, and the
      # l2tp plugin ships its vpn dialog as a gtk editor this picks up.
      environment.systemPackages = lib.optional (has "ui") pkgs.networkmanagerapplet;
    }

    (lib.mkIf cfg.profile {
      networking.networkmanager.ensureProfiles = {
        environmentFiles = [ cfg.secretsFile ];

        # envsubst runs over this on activation, so the $-variables are the only
        # things that never touch the store. The profile lands in
        # /run/NetworkManager/system-connections and is read-only to the gui;
        # editing it there makes networkmanager fork a second, persistent copy.
        profiles.work-vpn = {
          connection = {
            id = "work";
            uuid = "748968cb-7e45-4072-bc4c-1417279bd2b3";
            type = "vpn";
            autoconnect = false;
          };

          vpn = {
            service-type = "org.freedesktop.NetworkManager.l2tp";
            gateway = "$WORK_VPN_GATEWAY";
            user = "$WORK_VPN_USER";
            domain = "$WORK_VPN_DOMAIN";
            user-auth-type = "password";
            password-flags = 0;
            ipsec-enabled = "yes";
            machine-auth-type = "psk";
            ipsec-psk-flags = 0;
          };

          vpn-secrets = {
            password = "$WORK_VPN_PASSWORD";
            ipsec-psk = "$WORK_VPN_PSK";
          };

          ipv4.method = "auto";
          ipv6 = {
            method = "auto";
            addr-gen-mode = "stable-privacy";
          };
        };
      };
    })
  ]);
}
